#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["api/WebCv.Api/WebCv.Api.csproj", "api/WebCv.Api/"]
RUN dotnet restore "api/WebCv.Api/WebCv.Api.csproj"
COPY . .
WORKDIR "/src/api/WebCv.Api"
RUN dotnet build "WebCv.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebCv.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebCv.Api.dll"]
